# Generated by Django 5.0 on 2023-12-12 09:13

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0009_remove_category_file_remove_category_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('original_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='uploads/product')),
                ('short_description', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('description', ckeditor.fields.RichTextField()),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategory', to='category.subsubcategory')),
            ],
        ),
    ]
