# Generated by Django 5.0 on 2023-12-13 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_size_remove_product_stock_productvariation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/productVariation')),
                ('product_variation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variation_images', to='products.productvariation')),
            ],
        ),
        migrations.AddField(
            model_name='productvariation',
            name='images',
            field=models.ManyToManyField(related_name='product_variation_images', to='products.productvariationimage'),
        ),
    ]
