# Generated by Django 5.0 on 2023-12-25 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productvariation_selling_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/productVariation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='products.product')),
            ],
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='images',
            field=models.ManyToManyField(related_name='product_images', to='products.productimage'),
        ),
        migrations.DeleteModel(
            name='ProductVariationImage',
        ),
    ]
