# Generated by Django 5.0 on 2023-12-27 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_productvariation_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariation',
            name='images',
        ),
    ]
