# Generated by Django 5.0 on 2024-02-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_producttag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductTag',
        ),
    ]
