# Generated by Django 5.0 on 2024-02-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_producttag'),
        ('products', '0014_delete_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tag',
            field=models.ManyToManyField(to='category.producttag'),
        ),
    ]
