# Generated by Django 5.0.2 on 2024-03-07 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0016_producttag'),
        ('products', '0015_product_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subsubcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_subcategory', to='category.subcategory'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='subsubcategory_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subsubcategory', to='category.subsubcategory'),
        ),
    ]
