# Generated by Django 5.0 on 2023-12-07 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=1, upload_to='category_icon'),
            preserve_default=False,
        ),
    ]
