# Generated by Django 5.0 on 2023-12-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_subsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(upload_to='category_icon'),
        ),
    ]
