# Generated by Django 5.0 on 2023-12-07 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='reer',
            field=models.FileField(default=1, upload_to='category_icon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(upload_to='category_icon'),
        ),
    ]
