# Generated by Django 5.0 on 2023-12-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0006_category_reer_alter_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='reer',
        ),
        migrations.AddField(
            model_name='category',
            name='file',
            field=models.FileField(default=1, upload_to='attachments'),
            preserve_default=False,
        ),
    ]
