# Generated by Django 5.0 on 2023-12-11 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_remove_category_reer_category_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='video',
            field=models.FileField(default=1, upload_to='video'),
            preserve_default=False,
        ),
    ]
