# Generated by Django 5.0 on 2023-12-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_category_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='file',
        ),
        migrations.RemoveField(
            model_name='category',
            name='video',
        ),
    ]
