# Generated by Django 5.0 on 2024-01-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsubcategory',
            name='banner',
            field=models.ImageField(default=1, upload_to='uploads/subsubcategory_banner'),
            preserve_default=False,
        ),
    ]
