# Generated by Django 5.0 on 2024-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0014_remove_subsubcategory_banner_category_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
