# Generated by Django 5.0 on 2023-12-31 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_qty',
            new_name='product_quantity',
        ),
    ]
