# Generated by Django 5.0 on 2023-12-31 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_product_qty_cart_product_quantity'),
        ('products', '0009_remove_productvariation_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvariation'),
        ),
    ]
