# Generated by Django 5.0 on 2024-01-10 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='social_media_links',
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='facebook',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
