# Generated by Django 5.0 on 2024-01-10 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_siteinfo_social_media_links_siteinfo_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='instagram',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(default=1, upload_to='uploads/site_info'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='pinterest',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='twitter',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteinfo',
            name='youtube',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='facebook',
            field=models.URLField(),
        ),
    ]
