# Generated by Django 5.0 on 2024-01-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_siteinfo_instagram_siteinfo_logo_siteinfo_pinterest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='nav_background',
            field=models.ImageField(default=1, upload_to='uploads/core'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(upload_to='uploads/core'),
        ),
    ]
