# Generated by Django 5.0 on 2024-01-11 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_siteinfo_nav_background_alter_siteinfo_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='video',
            field=models.FileField(default=1, upload_to='uploads/core'),
            preserve_default=False,
        ),
    ]
