# Generated by Django 5.0 on 2024-01-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteinfo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='title_fav_icon',
            field=models.ImageField(default=1, upload_to='uploads/site_settings'),
            preserve_default=False,
        ),
    ]
