# Generated by Django 5.0 on 2024-02-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteinfo_featured_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='welcome_message',
            field=models.CharField(default='Welcome to BengalVibes', max_length=50),
            preserve_default=False,
        ),
    ]
