# Generated by Django 5.0 on 2024-02-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_siteinfo_welcome_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='video_caption',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
