# Generated by Django 5.0 on 2024-02-07 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteinfo_video_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='best_seller_banner',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/core'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='featured_banner',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/core'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/core'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='nav_background',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/core'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='new_arrival_banner',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/core'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='title_fav_icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/site_settings'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/core'),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='video_caption',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='welcome_message',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
