# Generated by Django 5.0 on 2024-02-11 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_siteinfo_best_seller_banner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='video',
        ),
        migrations.RemoveField(
            model_name='siteinfo',
            name='video_caption',
        ),
    ]
