# Generated by Django 5.0 on 2024-01-13 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_video_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='video_advertisement',
            name='caption',
            field=models.CharField(default='BengalVibes', max_length=50),
            preserve_default=False,
        ),
    ]
