# Generated by Django 5.0 on 2024-01-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_video_advertisement_caption'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='video_advertisement',
            new_name='VideoAdvertisement',
        ),
    ]
