# Generated by Django 5.0 on 2024-01-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_rename_video_advertisement_videoadvertisement'),
        ('products', '0009_remove_productvariation_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalBannerAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('banner', models.ImageField(upload_to='uploads/verticalbanner')),
                ('url', models.URLField()),
                ('products', models.ManyToManyField(related_name='vertical_banners_product', to='products.product')),
            ],
        ),
    ]
