# Generated by Django 5.0 on 2024-01-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0005_verticalbanneradvertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='verticalbanneradvertisement',
            name='position',
            field=models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
