# Generated by Django 5.0 on 2024-01-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0006_verticalbanneradvertisement_position'),
        ('products', '0009_remove_productvariation_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VerticalBannerAdvertisement',
            new_name='VerticalBannerProudctAdvertisement',
        ),
    ]
