# Generated by Django 5.0 on 2024-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_rename_verticalbanneradvertisement_verticalbannerproudctadvertisement'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalBannerAdvertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='uploads/verticalad')),
                ('url', models.URLField()),
            ],
        ),
    ]
